quarkus.otel.traces.exporter=none

mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources

streamx.url-include-replacement-provider=SsiInclude
streamx.blueprints.openai-rag-sink.html-resource-types=\
com.streamx.blueprints.page.published.v1,\
com.streamx.blueprints.page.unpublished.v1,\
com.streamx.blueprints.fragment.published.v1,\
com.streamx.blueprints.fragment.unpublished.v1

quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=pgvector/pgvector:pg17

quarkus.langchain4j.openai.api-key=test-key
quarkus.langchain4j.openai.base-url=http://localhost:${quarkus.wiremock.devservices.port:11434}/v1

quarkus.langchain4j.pgvector.dimension=1536